# 1D Array

In [1]:
import numpy as np
meat=np.array(["fish","chicken","mutton"])
meat

array(['fish', 'chicken', 'mutton'], dtype='<U7')

In [2]:
num=np.array([10,5,15])
num

array([10,  5, 15])

In [3]:
type(num)

numpy.ndarray

In [4]:
len(num)

3

In [5]:
num[2]

15

In [6]:
num[0:]

array([10,  5, 15])

In [7]:
num[1]

5

In [8]:
num.mean()

10.0

In [9]:
#Zeros method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
#ones array
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [16]:
#empty array
np.empty(1, dtype=int)

array([0])

In [52]:
np.empty(6, dtype=int)

array([640702400,       452, 574198224,       452,    131074,         0])

In [21]:
#defining array 
np.arange(18)
#specifying range
np.arange(5,25)
#specifying range and interval
np.arange(2,22,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
#generating random data between a specific range but with same difference between relavent numbers
np.linspace(1,50,num=150)

array([ 1.        ,  1.32885906,  1.65771812,  1.98657718,  2.31543624,
        2.6442953 ,  2.97315436,  3.30201342,  3.63087248,  3.95973154,
        4.2885906 ,  4.61744966,  4.94630872,  5.27516779,  5.60402685,
        5.93288591,  6.26174497,  6.59060403,  6.91946309,  7.24832215,
        7.57718121,  7.90604027,  8.23489933,  8.56375839,  8.89261745,
        9.22147651,  9.55033557,  9.87919463, 10.20805369, 10.53691275,
       10.86577181, 11.19463087, 11.52348993, 11.85234899, 12.18120805,
       12.51006711, 12.83892617, 13.16778523, 13.4966443 , 13.82550336,
       14.15436242, 14.48322148, 14.81208054, 15.1409396 , 15.46979866,
       15.79865772, 16.12751678, 16.45637584, 16.7852349 , 17.11409396,
       17.44295302, 17.77181208, 18.10067114, 18.4295302 , 18.75838926,
       19.08724832, 19.41610738, 19.74496644, 20.0738255 , 20.40268456,
       20.73154362, 21.06040268, 21.38926174, 21.71812081, 22.04697987,
       22.37583893, 22.70469799, 23.03355705, 23.36241611, 23.69

In [28]:
#specifying data type
np.ones(4, dtype=np.int32)

array([1, 1, 1, 1])

In [31]:
np.ones(10, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Functions of Array 

In [35]:
a= np.array([10,50,140,9.9])
a

array([ 10. ,  50. , 140. ,   9.9])

In [37]:
a.sort()
a

array([  9.9,  10. ,  50. , 140. ])

In [38]:
b=np.array([4.8,70,12,2.5])
b

array([ 4.8, 70. , 12. ,  2.5])

In [40]:
c=np.concatenate((a,b))
c

array([  9.9,  10. ,  50. , 140. ,   4.8,  70. ,  12. ,   2.5])

In [42]:
c.sort()
c

array([  2.5,   4.8,   9.9,  10. ,  12. ,  50. ,  70. , 140. ])

# 2-D Array

In [58]:
a=np.array([[5,4,3,2,1],[1,2,3,4,5],[10,4,35,66,5]])
a

array([[ 5,  4,  3,  2,  1],
       [ 1,  2,  3,  4,  5],
       [10,  4, 35, 66,  5]])

In [59]:
a.size

15

In [60]:
a.shape

(3, 5)

In [45]:
b=np.array([[15,14,13,12,11],[11,12,13,14,15]])
b

array([[15, 14, 13, 12, 11],
       [11, 12, 13, 14, 15]])

In [62]:
c=np.concatenate((a,b), axis=0)
c

array([[ 5,  4,  3,  2,  1],
       [ 1,  2,  3,  4,  5],
       [10,  4, 35, 66,  5],
       [15, 14, 13, 12, 11],
       [11, 12, 13, 14, 15]])

In [49]:
c.sort()
c

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15]])

In [50]:
d=c*2
d

array([[ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30],
       [22, 24, 26, 28, 30]])

In [51]:
#To find the num of dimensions
d.ndim

2

In [54]:
# size of array
d.size

20

In [57]:
#shape of array
a.shape
d.shape
c.shape

(4, 5)

In [63]:
x=np.array([[2,5],[6,8]])
x

array([[2, 5],
       [6, 8]])

In [64]:
y=np.array([[2,3],[9,8]])
y

array([[2, 3],
       [9, 8]])

In [77]:
#mentioning axis=0 the stacking is vertical
z=np.concatenate((x,y), axis=0)
z

array([[2, 5],
       [6, 8],
       [2, 3],
       [9, 8]])

In [78]:
len(z)

4

In [75]:
#mentioning axis=1 the stacking is horizontal
l=np.concatenate((x,y), axis=1)
l

array([[2, 5, 2, 3],
       [6, 8, 9, 8]])

In [76]:
len(l)

2

# 3D Array

In [81]:
j=np.array([[[2,3],
            [6,2]],
           [[9,7],
            [1,6]],
           [[7,4],
            [5,1]]])
j

array([[[2, 3],
        [6, 2]],

       [[9, 7],
        [1, 6]],

       [[7, 4],
        [5, 1]]])

In [84]:
j.ndim

3

In [85]:
#number of elements
j.size

12

In [86]:
j.shape

(3, 2, 2)

In [88]:
#a is 3*4 that is why the parameters are this
j.reshape(3,4)

array([[2, 3, 6, 2],
       [9, 7, 1, 6],
       [7, 4, 5, 1]])

In [89]:
np.reshape(j, newshape=(1,12), order ='C')

array([[2, 3, 6, 2, 9, 7, 1, 6, 7, 4, 5, 1]])

In [90]:
#row wise 2D conversion
k=j[np.newaxis,:]
k

array([[[[2, 3],
         [6, 2]],

        [[9, 7],
         [1, 6]],

        [[7, 4],
         [5, 1]]]])

In [91]:
#column wise 2D conversion
o=j[:, np.newaxis]
o

array([[[[2, 3],
         [6, 2]]],


       [[[9, 7],
         [1, 6]]],


       [[[7, 4],
         [5, 1]]]])

In [97]:
#array slicing
o[1:2]

array([[[[9, 7],
         [1, 6]]]])

In [98]:
o.sum()

53

In [99]:
o.mean()

4.416666666666667

In [100]:
o*2

array([[[[ 4,  6],
         [12,  4]]],


       [[[18, 14],
         [ 2, 12]]],


       [[[14,  8],
         [10,  2]]]])

In [101]:
o+2

array([[[[ 4,  5],
         [ 8,  4]]],


       [[[11,  9],
         [ 3,  8]]],


       [[[ 9,  6],
         [ 7,  3]]]])

# General practice

In [102]:
a

array([[ 5,  4,  3,  2,  1],
       [ 1,  2,  3,  4,  5],
       [10,  4, 35, 66,  5]])

In [105]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [106]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [107]:
a2.shape


(1, 6)

In [111]:
a2.ndim

2

In [112]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [113]:
a2[0]

array([0, 1, 2, 3, 4, 5])

In [115]:
a2=np.array([[1,2,3,4],[6,7,8,9]])
a2

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [117]:
a2[1]

array([6, 7, 8, 9])

In [118]:
np.zeros(4)

array([0., 0., 0., 0.])

In [119]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [124]:
np.empty(2, dtype=np.int64)

array([1941965920192,             0], dtype=int64)